### ISSUE TITLE
about training question

### ISSUE THREAD

**Issue by alexliyang** [96imranahmed/faceboxes_tf#1]
@96imranahmed： 
    thank you for your reference code.
    I use your code training the model, and I set is_aug = False,  but ,the training convergence is to 7 than up and down, and mAP is always zero.
   how can I do for the model?
   Do you have the model and share it ?

**Comment by 96imranahmed** [comment]
Hey @alexliyang, thanks for posting!

So setting `is_aug` to false essentially just samples directly from the WIDER dataset and randomly pads the input images to the expected 1024 x 1024 input size. I don't think that this should affect training, though it would result in overfitting to the input dataset.

My recommendation is to leave the model training for a while as the model's mAP does begin to creep-up eventually (i.e. after 50k iterations at least) but it remains 0 for the first few 20-30k iterations. I would share my model, but it hasn't really trained as yet (I'm training on quite an aggressive augmentation strategy, as I need in-plane rotation invariance). That being said, I did just try the semi-trained model this morning on my webcam, and it does appear to work for large faces. 

Do let me know if you need any more help getting things to work! A fair amount of hyperparameter tuning may be needed so please do have a tweak around! :)

**Comment by alexliyang** [comment]
Thank you very much!
haha, I will try again.
